### PR TITLE
Merge resque/master

### PR DESCRIPTION
**Pull request by bdragon**
Updates this branch so that https://github.com/resque/resque/pull/1617 can be merged. Four years, not too shabby!

### CODE REVIEW

**Comment by Alex-Quinn** [comment]
🎉 🎉 🎉 Thanks @bdragon! 🙏

**Comment by Murphydbuffalo** [comment]
Thanks dude!

**Comment by Alex-Quinn** [comment]
@bdragon I granted you access to the wunderteam resque fork. Let me know if I can do anything else to get this across the line. Thanks again!

**Comment by bdragon** [comment]
Thanks @Alex-Quinn I just rebased the branch against upstream/master, resolved conflicts, and went to push --force-with-lease and... apparently the invitation has expired. Sorry! It's ready to go if you don't mind re-sending.

**Comment by Alex-Quinn** [comment]
@bdragon no problem, thanks for tackling this. Invite sent!

**Comment by bdragon** [comment]
@Alex-Quinn Thanks, the upstream PR is updated. Now just waiting on a maintainer to approve it... if we're lucky it might get merged by 2025

**Pull request closed without merging**
